name: task1
on: push
jobs:
  task1:
     runs-on: ubuntu-latest
     steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: download dependencies
        run: npm install
      - name: run lint
        run: npm run lint
      - name: build
        run: npm run build
  task2:
     needs: task1
     runs-on: ubuntu-latest
     steps:
      - name: deploy
        run: echo "Deployement"

        